build:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  image: python:3.13
  variables:
    TWINE_REPO: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
    TWINE_USERNAME: "gitlab-ci-token"
    TWINE_PASSWORD: "${CI_JOB_TOKEN}"
  before_script:
    - echo -e "machine gitup.uni-potsdam.de login gitlab-ci-token password ${CI_JOB_TOKEN}" > ~/.netrc
  script:
    - apt-get update && apt-get install -y default-jdk libsaxonhe-java sfst
    - python3 -m venv .venv && source .venv/bin/activate
    - pip install -r requirements.dev.txt
    - python -m dwdsmor.build.dwds.release
  tags:
    - zdl
    - build
