import os
import csv
import dwdsmor
from collections import namedtuple, defaultdict

# mapping between divergent STTS and SMOR part-of-speech categories
TUEBADZ_DWDSMOR_POS_MAP = {"ADJA":    ["ADJ", "INDEF", "CARD", "ORD"],
                           "ADJD":    ["ADJ"],
                           "ADV":     ["ADV", "ADJ"],
                           "APPO":    ["POSTP"],
                           "APPR":    ["PREP"],
                           "APPRART": ["PREPART"],
                           "APZR":    ["POSTP", "PREP"],
                           "ITJ":     ["INTJ"],
                           "KOKOM":   ["CONJ"],
                           "KON":     ["CONJ"],
                           "KOUI":    ["CONJ"],
                           "KOUS":    ["CONJ"],
                           "NE":      ["NPROP"],
                           "NN":      ["NN", "NPROP"],
                           "PDAT":    ["DEM"],
                           "PDS":     ["DEM"],
                           "PIAT":    ["INDEF"],
                           "PIDAT":   ["INDEF"],
                           "PIS":     ["INDEF"],
                           "PPER":    ["PPRO"],
                           "PPOSAT":  ["POSS"],
                           "PPOSS":   ["POSS"],
                           "PRELAT":  ["REL"],
                           "PRELS":   ["REL"],
                           "PRF":     ["PPRO"],
                           "PROP":    ["PROADV", "ADV"],
                           "PTKA":    ["PTCL"],
                           "PTKANT":  ["PTCL", "INTJ"],
                           "PTKNEG":  ["PTCL"],
                           "PTKVZ":   ["VPART", "ADV", "PREP"],
                           "PTKZU":   ["PTCL"],
                           "PWAT":    ["WPRO"],
                           "PWAV":    ["ADV"],
                           "PWS":     ["WPRO"],
                           "VAFIN":   ["V"],
                           "VAIMP":   ["V"],
                           "VAINF":   ["V"],
                           "VAPP":    ["V"],
                           "VMFIN":   ["V"],
                           "VMINF":   ["V"],
                           "VMPP":    ["V"],
                           "VVFIN":   ["V"],
                           "VVIMP":   ["V"],
                           "VVINF":   ["V"],
                           "VVIZU":   ["V"],
                           "VVPP":    ["V"]}

# mapping between divergent TüBa-D/Z and DWDSmor lemmas
TUEBADZ_DWDSMOR_LEMMA_MAP = {"ADJA": {"acht": "achte",
                                      "älter": "alt",
                                      "ältst": "alt",
                                      "besser": "gut",
                                      "best": "gut",
                                      "dritt": "dritte",
                                      "ein": "eine",
                                      "elft": "elfte",
                                      "erst": "erste",
                                      "fünft": "fünfte",
                                      "größer": "groß",
                                      "größt": "groß",
                                      "höher": "hoch",
                                      "höchst": "hoch",
                                      "jünger": "jung",
                                      "jüngst": "jung",
                                      "kleiner": "klein",
                                      "kleinst": "klein",
                                      "länger": "lang",
                                      "längst": "lang",
                                      "links": "link",
                                      "nächst": "nahe",
                                      "näher": "nahe",
                                      "neuer": "neu",
                                      "neuest": "neu",
                                      "neunt": "neunte",
                                      "rechts": "recht",
                                      "schlimmer": "schlimm",
                                      "schlimmst": "schlimm",
                                      "schneller": "schnell",
                                      "schnellst": "schnell",
                                      "sechst": "sechste",
                                      "siebt": "siebte",
                                      "stärker": "stark",
                                      "teurer": "teuer",
                                      "teuerst": "teuer",
                                      "viert": "vierte",
                                      "wichtiger": "wichtig",
                                      "wichtigst": "wichtig",
                                      "zehnt": "zehnte",
                                      "zweit": "zweite",
                                      "zwölft": "zwölfte"},
                             "ADJD": {"älter": "alt",
                                      "ältst": "alt",
                                      "besser": "gut",
                                      "best": "gut",
                                      "billiger": "billig",
                                      "größer": "groß",
                                      "größt": "groß",
                                      "höher": "hoch",
                                      "höchst": "hoch",
                                      "jünger": "jung",
                                      "jüngst": "jung",
                                      "kleiner": "klein",
                                      "kleinst": "klein",
                                      "länger": "lang",
                                      "längst": "lang",
                                      "leichter": "leicht",
                                      "meisten": "viel",
                                      "nächst": "nahe",
                                      "näher": "nahe",
                                      "neuer": "neu",
                                      "neuest": "neu",
                                      "schlimmer": "schlimm",
                                      "schlimmst": "schlimm",
                                      "schneller": "schnell",
                                      "schnellst": "schnell",
                                      "später": "spät",
                                      "stärker": "stark",
                                      "teurer": "teuer",
                                      "teuerst": "teuer",
                                      "voller": "voll",
                                      "wichtiger": "wichtig",
                                      "wichtigst": "wichtig"},
                             "ADV": {"eher": "bald",
                                     "lieber": "gerne",
                                     "mehr": "sehr",
                                     "öfter": "oft",
                                     "weiter": "weit",
                                     "weniger": "wenig"},
                             "ART": {"das": "die",
                                     "der": "die",
                                     "der|die|das": "die",
                                     "ein": "eine",
                                     "ein|eine": "eine"},
                             "NN": {"Abgeordneter": "Abgeordnete",
                                    "Abgeordneter|Abgeordnete|Abgeordnetes": "Abgeordnete",
                                    "Abhängiger": "Abhängige",
                                    "Abhängiger|Abhängige|Abhängiges": "Abhängige",
                                    "Alliierter": "Alliierte",
                                    "Alliierter|Alliierte|Alliiertes": "Alliierte",
                                    "Alter": "Alte",
                                    "Alter|Alte|Altes": "Alte",
                                    "Älterer": "Ältere",
                                    "Älterer|Ältere|Älteres": "Ältere",
                                    "Angehöriger": "Angehörige",
                                    "Angehöriger|Angehörige|Angehöriges": "Angehörige",
                                    "Angeklagter": "Angeklagte",
                                    "Angeklagter|Angeklagte|Angeklagtes": "Angeklagte",
                                    "Angestellter": "Angestellte",
                                    "Angestellter|Angestellte|Angestelltes": "Angestellte",
                                    "Aufständischer": "Aufständische",
                                    "Aufständischer|Aufständische|Aufständisches": "Aufständische",
                                    "Autonomer": "Autonome",
                                    "Autonomer|Autonome|Autonomes": "Autonome",
                                    "Beamter": "Beamte",
                                    "Bediensteter": "Bedienstete",
                                    "Bediensteter|Bedienstete|Bedienstetes": "Bedienstete",
                                    "Befragter": "Befragte",
                                    "Befragter|Befragte|Befragtes": "Befragte",
                                    "Behinderter": "Behinderte",
                                    "Behinderter|Behinderte|Behindertes": "Behinderte",
                                    "Bekannter": "Bekannte",
                                    "Bekannter|Bekannte|Bekanntes": "Bekannte",
                                    "Beschäftigter": "Beschäftigte",
                                    "Beschäftigter|Beschäftigte|Beschäftigtes": "Beschäftigte",
                                    "Beschuldigter": "Beschuldigte",
                                    "Beschuldigter|Beschuldigte|Beschuldigtes": "Beschuldigte",
                                    "Bester": "Beste",
                                    "Bestes": "Beste",
                                    "Bester|Beste|Bestes": "Beste",
                                    "Beteiligter": "Beteiligte",
                                    "Beteiligter|Beteiligte|Beteiligtes": "Beteiligte",
                                    "Betroffener": "Betroffene",
                                    "Betroffener|Betroffene|Betroffenes": "Betroffene",
                                    "Blinder": "Blinde",
                                    "Blinder|Blinde|Blindes": "Blinde",
                                    "Bundestagsabgeordneter": "Bundestagsabgeordnete",
                                    "Bundestagsabgeordneter|Bundestagsabgeordnete|Bundestagsabgeordnetes": "Bundestagsabgeordnete",
                                    "Bündnisgrüner": "Bündnisgrüne",
                                    "Bündnisgrüner|Bündnisgrüne|Bündnisgrünes": "Bündnisgrüne",
                                    "Delegierter": "Delegierte",
                                    "Delegierter|Delegierte|Delegiertes": "Delegierte",
                                    "Deutscher": "Deutsche",
                                    "Deutsches": "Deutsche",
                                    "Deutscher|Deutsche|Deutsches": "Deutsche",
                                    "Dritter": "Dritte",
                                    "Drittes": "Dritte",
                                    "Dritter|Dritte|Drittes": "Dritte",
                                    "Drogenabhängiger": "Drogenabhängige",
                                    "Drogenabhängiger|Drogenabhängige|Drogenabhängiges": "Drogenabhängige",
                                    "Drogensüchtiger": "Drogensüchtige",
                                    "Drogensüchtiger|Drogensüchtige|Drogensüchtiges": "Drogensüchtige",
                                    "Eingeborener": "Eingeborene",
                                    "Eingeborener|Eingeborene|Eingeborenes": "Eingeborene",
                                    "Einheimischer": "Einheimische",
                                    "Einheimischer|Einheimische|Einheimisches": "Einheimische",
                                    "Erster": "Erste",
                                    "Erstes": "Erste",
                                    "Erster|Erste|Erstes": "Erste",
                                    "Erwachsener": "Erwachsene",
                                    "Erwachsener|Erwachsene|Erwachsenes": "Erwachsene",
                                    "Familienangehöriger": "Familienangehörige",
                                    "Familienangehöriger|Familienangehörige|Familienangehöriges": "Familienangehörige",
                                    "Fraktionsvorsitzender": "Fraktionsvorsitzende",
                                    "Fraktionsvorsitzender|Fraktionsvorsitzende|Fraktionsvorsitzendes": "Fraktionsvorsitzende",
                                    "Freies": "Freie",
                                    "Freier|Freie|Freies": "Freie",
                                    "Freiwilliger": "Freiwillige",
                                    "Freiwilliger|Freiwillige|Freiwilliges": "Freiwillige",
                                    "Fremder": "Fremde",
                                    "Fremder|Fremde|Fremdes": "Fremde",
                                    "Ganzes": "Ganze",
                                    "Ganzer|Ganze|Ganzes": "Ganze",
                                    "Gefangener": "Gefangene",
                                    "Gefangener|Gefangene|Gefangenes": "Gefangene",
                                    "Gläubiger": "Gläubige",
                                    "Gläubiger|Gläubige|Gläubiges": "Gläubige",
                                    "Gleicher": "Gleiche",
                                    "Gleiches": "Gleiche",
                                    "Gleicher|Gleiche|Gleiches": "Gleiche",
                                    "Geschworener": "Geschworene",
                                    "Geschworener|Geschworene|Geschworenes": "Geschworene",
                                    "Grüner": "Grüne",
                                    "Grüner|Grüne|Grünes": "Grüne",
                                    "Herrschender": "Herrschende",
                                    "Herrschender|Herrschende|Herrschendes": "Herrschende",
                                    "Heterosexueller": "Heterosexuelle",
                                    "Heterosexueller|Heterosexuelle|Heterosexuelles": "Heterosexuelle",
                                    "Hinterbliebener": "Hinterbliebene",
                                    "Hinterbliebener|Hinterbliebene|Hinterbliebenes": "Hinterbliebene",
                                    "Homosexueller": "Homosexuelle",
                                    "Homosexueller|Homosexuelle|Homosexuelles": "Homosexuelle",
                                    "Inhaftierter": "Inhaftierte",
                                    "Inhaftierter|Inhaftierte|Inhaftiertes": "Inhaftierte",
                                    "Innerer": "Innere",
                                    "Inneres": "Innere",
                                    "Innerer|Innere|Inneres": "Innere",
                                    "Intellektueller": "Intellektuelle",
                                    "Intellektueller|Intellektuelle|Intellektuelles": "Intellektuelle",
                                    "Jugendlicher": "Jugendliche",
                                    "Jugendlicher|Jugendliche|Jugendliches": "Jugendliche",
                                    "Junger": "Junge",
                                    "Junger|Junge|Junges": "Junge",
                                    "Jüngerer": "Jüngere",
                                    "Jüngerer|Jüngere|Jüngeres": "Jüngere",
                                    "Kranker": "Kranke",
                                    "Kranker|Kranke|Krankes": "Kranke",
                                    "Kreisvorsitzender": "Kreisvorsitzende",
                                    "Kreisvorsitzender|Kreisvorsitzende|Kreisvorsitzendes": "Kreisvorsitzende",
                                    "Krimineller": "Kriminelle",
                                    "Krimineller|Kriminelle|Kriminelles": "Kriminelle",
                                    "Konservativer": "Konservative",
                                    "Konservativer|Konservative|Konservatives": "Konservative",
                                    "Kulturschaffender": "Kulturschaffende",
                                    "Kulturschaffender|Kulturschaffende|Kulturschaffendes": "Kulturschaffende",
                                    "Landesvorsitzender": "Landesvorsitzende",
                                    "Landesvorsitzender|Landesvorsitzende|Landesvorsitzendes": "Landesvorsitzende",
                                    "Lebender|Lebende|Lebendes": "Lebende",
                                    "Lehrender": "Lehrende",
                                    "Lehrender|Lehrende|Lehrendes": "Lehrende",
                                    "Liberaler": "Liberale",
                                    "Liberaler|Liberale|Liberales": "Liberale",
                                    "Linker": "Linke",
                                    "Linker|Linke|Linkes": "Linke",
                                    "Mächtiger": "Mächtige",
                                    "Mächtiger|Mächtige|Mächtiges": "Mächtige",
                                    "Minderjähriger": "Minderjährige",
                                    "Minderjähriger|Minderjährige|Minderjähriges": "Minderjährige",
                                    "Offizieller": "Offizielle",
                                    "Offizieller|Offizielle|Offizielles": "Offizielle",
                                    "Oppositioneller": "Oppositionelle",
                                    "Oppositioneller|Oppositionelle|Oppositionelles": "Oppositionelle",
                                    "Orthodoxer": "Orthodoxe",
                                    "Orthodoxer|Orthodoxe|Orthodoxes": "Orthodoxe",
                                    "Ostdeutscher": "Ostdeutsche",
                                    "Ostdeutscher|Ostdeutsche|Ostdeutsches": "Ostdeutsche",
                                    "Parteivorsitzender": "Parteivorsitzende",
                                    "Parteivorsitzender|Parteivorsitzende|Parteivorsitzendes": "Parteivorsitzende",
                                    "Polizeibeamter": "Polizeibeamte",
                                    "Prominenter": "Prominente",
                                    "Prominenter|Prominente|Prominentes": "Prominente",
                                    "Prostituierter": "Prostituierte",
                                    "Prostituierter|Prostituierte|Prostituiertes": "Prostituierte",
                                    "Protestierender": "Protestierende",
                                    "Protestierender|Protestierende|Protestierendes": "Protestierende",
                                    "Rechter": "Rechte",
                                    "Rechter|Rechte|Rechtes": "Rechte",
                                    "Regierender": "Regierende",
                                    "Regierender|Regierende|Regierendes": "Regierende",
                                    "Reisender": "Reisende",
                                    "Reisender|Reisende|Reisendes": "Reisende",
                                    "Sachverständiger": "Sachverständige",
                                    "Sachverständiger|Sachverständige|Sachverständiges": "Sachverständige",
                                    "Schwarzer": "Schwarze",
                                    "Schwarzes": "Schwarze",
                                    "Schwarzer|Schwarze|Schwarzes": "Schwarze",
                                    "Schwuler": "Schwule",
                                    "Schwuler|Schwule|Schwules": "Schwule",
                                    "Sozialer": "Soziale",
                                    "Soziales": "Soziale",
                                    "Sozialer|Soziale|Soziales": "Soziale",
                                    "Standesbeamter": "Standesbeamte",
                                    "Streikender": "Streikende",
                                    "Streikender|Streikende|Streikendes": "Streikende",
                                    "Studierender": "Studierende",
                                    "Studierender|Studierende|Studierendes": "Studierende",
                                    "Süchtiger|Süchtige|Süchtiges": "Süchtige",
                                    "Toter": "Tote",
                                    "Toter|Tote|Totes": "Tote",
                                    "Überlebender": "Überlegende",
                                    "Überlebender|Überlebende|Überlebendes": "Überlegende",
                                    "Unbekannter": "Unbekannte",
                                    "Unbekannter|Unbekannte|Unbekanntes": "Unbekannte",
                                    "Verantwortlicher": "Verantwortliche",
                                    "Verantwortlicher|Verantwortliche|Verantwortliches": "Verantwortliche",
                                    "Verbündeter": "Verbündete",
                                    "Verbündeter|Verbündete|Verbündetes": "Verbündete",
                                    "Verdächtiger": "Verdächtige",
                                    "Verdächtiger|Verdächtige|Verdächtiges": "Verdächtige",
                                    "Verfolgter": "Verfolgte",
                                    "Verfolgter|Verfolgte|Verfolgtes": "Verfolgte",
                                    "Verletzter": "Verletzte",
                                    "Verletzter|Verletzte|Verletztes": "Verletzte",
                                    "Vertriebener": "Vertriebene",
                                    "Vertriebener|Vertriebene|Vertriebenes": "Vertriebene",
                                    "Verurteilter": "Verurteilte",
                                    "Verurteilter|Verurteilte|Verurteiltes": "Verurteilte",
                                    "Verwandter": "Verwandte",
                                    "Verwandter|Verwandte|Verwandtes": "Verwandte",
                                    "Vorgesetzter": "Vorgesetzte",
                                    "Vorgesetzter|Vorgesetzte|Vorgesetztes": "Vorgesetzte",
                                    "Vorsitzender": "Vorsitzende",
                                    "Vorsitzender|Vorsitzende|Vorsitzendes": "Vorsitzende",
                                    "Vorstandsvorsitzender": "Vorstandsvorsitzende",
                                    "Vorstandsvorsitzender|Vorstandsvorsitzende|Vorstandsvorsitzendes": "Vorstandsvorsitzende",
                                    "Wahlberechtigter": "Wahlberechtigte",
                                    "Wahlberechtigter|Wahlberechtigte|Wahlberechtigtes": "Wahlberechtigte",
                                    "Weißer": "Weiße",
                                    "Weißer|Weiße|Weißes": "Weiße",
                                    "Zweiter": "Zweite",
                                    "Zweites": "Zweite",
                                    "Zweiter|Zweite|Zweites": "Zweite"},
                             "PDAT": {"alles": "alle",
                                      "dasjenige": "diejenige",
                                      "das": "die",
                                      "der": "die",
                                      "der|die|das": "die",
                                      "deren": "die",
                                      "derjenige": "diejenige",
                                      "derjenige|diejenige|dasjenige": "diejenige",
                                      "dessen": "die",
                                      "dessen|deren": "die",
                                      "dieser": "diese",
                                      "dieser|diese|dieses": "diese",
                                      "dieses": "diese",
                                      "jener": "jene",
                                      "jener|jene|jenes": "jene",
                                      "jenes": "jene"},
                             "PDS": {"dasjenige": "diejenige",
                                     "derjenige": "diejenige",
                                     "das": "die",
                                     "der": "die",
                                     "der|die|das": "die",
                                     "derjenige|diejenige|dasjenige": "diejenige",
                                     "dieser": "diese",
                                     "dieser|diese|dieses": "diese",
                                     "dieses": "diese"},
                             "PIAT": {"einiger": "einige",
                                      "einiger|einige|einiges": "einige",
                                      "einiges": "einige",
                                      "kein": "keine",
                                      "keiner": "keine",
                                      "kein|keine": "keine",
                                      "keines": "keine",
                                      "mancher": "manche",
                                      "mancher|manche|manches": "manche",
                                      "manches": "manche"},
                             "PIDAT": {"alles": "alle",
                                       "jeder": "jede",
                                       "jedes": "jede",
                                       "meisten": "viel",
                                       "meistes": "viel",
                                       "sämtlich": "sämtliche",
                                       "solcher": "solche",
                                       "solcher|solche|solches": "solche",
                                       "solches": "solche",
                                       "vieler": "viel",
                                       "vieler|viele|vieles": "viel",
                                       "vieles": "viel"},
                             "PIS": {"alles": "alle",
                                     "anderer": "ander",
                                     "anderer|andere|anderes": "ander",
                                     "anderes": "ander",
                                     "ein|eine": "eine",
                                     "einer": "eine",
                                     "eines": "eine",
                                     "einiges": "einige",
                                     "jeder": "jede",
                                     "jeder|jede|jedes": "jede",
                                     "jedes": "jede",
                                     "keiner": "keine",
                                     "keiner|keine|keines": "keine",
                                     "keines": "keine",
                                     "mancher": "manche",
                                     "mancher|manche|manches": "manche",
                                     "manches": "manche",
                                     "meisten": "viel",
                                     "meistes": "viel",
                                     "solcher": "solche",
                                     "solcher|solche|solches": "solche",
                                     "solches": "solche",
                                     "vieler": "viel",
                                     "vieler|viele|vieles": "viel",
                                     "vieles": "viel"},
                             "PPER": {"er|sie|es": "er"},
                             "PPOSAT": {"dein": "deine",
                                        "dein|deine": "deine",
                                        "deiner": "deine",
                                        "euer": "eure",
                                        "euer|eure": "eure",
                                        "ihr": "ihre",
                                        "ihr|ihre": "ihre",
                                        "mein": "meine",
                                        "mein|meine": "meine",
                                        "sein": "seine",
                                        "sein|seine": "seine",
                                        "unser": "unsere",
                                        "unser|unsere": "unsere"},
                             "PPOSS": {"deines": "deine",
                                       "ihres": "ihre",
                                       "meiner|meine|mein": "meine",
                                       "meines": "meine",
                                       "meiner": "meine",
                                       "seiner": "seine",
                                       "seiner|seine|seines": "seine",
                                       "seines": "seine",
                                       "unser": "unsere",
                                       "unserer": "unsere",
                                       "unserer|unsere|unseres": "unsere"},
                             "PRELAT": {"deren": "die",
                                        "dessen": "die",
                                        "dessen|deren": "die"},
                             "PRELS": {"das": "die",
                                       "der": "die",
                                       "der|die|das": "die"},
                             "PRF": {"dir": "dich",
                                     "mir": "mich"},
                             "PWAT": {"welcher": "welche",
                                      "welcher|welche|welches": "welche",
                                      "welches": "welche",
                                      "wievieler": "wieviele",
                                      "wievieler|wieviele|wievieles": "wieviele",
                                      "wievieles": "wieviele"}}

def tuebadz_to_dwdsmor_pos_list(pos):
    if pos in TUEBADZ_DWDSMOR_POS_MAP:
        return TUEBADZ_DWDSMOR_POS_MAP[pos]
    else:
        return pos

def tuebadz_to_dwdsmor_lemma(pos, lemma):
    if pos in TUEBADZ_DWDSMOR_LEMMA_MAP and lemma in TUEBADZ_DWDSMOR_LEMMA_MAP[pos]:
        return TUEBADZ_DWDSMOR_LEMMA_MAP[pos][lemma]
    else:
        return lemma

LemmatizedWord = namedtuple("LemmatizedWord", ("form",
                                               "lemma",
                                               "pos",
                                               "dwdsmor_lemma",
                                               "dwdsmor_pos",
                                               "is_match"))

def lemmatize(transducer, w):
    form, lemma, pos = (w.get("form", ""), w.get("lemma", ""), w.get("pos", ""))
    dwdsmor_lemma = ""
    dwdsmor_pos = ""
    if not (pos == "FM" or pos == "XY" or pos.startswith("$")):
        if pos == "PTKVZ" or lemma == "#refl":
            lemma = form
        lemma = lemma.split("%")[0]
        lemma = lemma.replace("#", "")
        analyses = tuple(dwdsmor.parse(transducer.analyse(form)))
        # analyses with matching part-of-speech categories
        analyses_with_matching_pos = tuple(a for a in analyses
                                           if a.pos in tuebadz_to_dwdsmor_pos_list(pos))
        # analyses with matching lemmas of matching part-of-speech categories
        analyses_with_matching_lemma = tuple(a for a in analyses_with_matching_pos
                                             if tuebadz_to_dwdsmor_lemma(pos, lemma) == a.lemma)
        # first consider analyses with matching lemmas of matching part-of-speech categories
        if len(analyses_with_matching_lemma) > 0:
            dwdsmor_lemma = analyses_with_matching_lemma[0].lemma
            dwdsmor_pos   = analyses_with_matching_lemma[0].pos
        # else consider any lemmas of matching part-of-speech categories
        elif len(analyses_with_matching_pos) > 0:
            dwdsmor_lemma = analyses_with_matching_pos[0].lemma
            dwdsmor_pos   = analyses_with_matching_pos[0].pos
    if (pos == "VAFIN" or pos == "VMFIN" or pos == "VVFIN" or pos == "VVIMP") and len(dwdsmor_lemma) > 0:
        # TüBa-D/Z lemmas for finite verb forms of particle verbs include the particle
        # while DWDSmor lemmas do not.
        is_match = tuebadz_to_dwdsmor_lemma(pos, lemma).endswith(dwdsmor_lemma)
    else:
        is_match = tuebadz_to_dwdsmor_lemma(pos, lemma) == dwdsmor_lemma
    return LemmatizedWord(form,
                          lemma,
                          pos,
                          dwdsmor_lemma,
                          dwdsmor_pos,
                          is_match)

def write_csv_report(csv_report_file, csv_header, csv_rows):
    csv_report_file.parent.mkdir(parents=True, exist_ok=True)
    with csv_report_file.open("w") as report_f:
        report_writer = csv.writer(report_f, lineterminator=os.linesep)
        report_writer.writerow(csv_header)
        for csv_row in csv_rows:
            report_writer.writerow(csv_row)

def test_tuebadz_coverage(project_dir, tuebadz, transducer):
    lemmatized = (lemmatize(transducer, w) for s in tuebadz for w in s)
    stats = defaultdict(lambda: defaultdict(int))
    for w in lemmatized:
        stats[w.pos][w.is_match] += 1
    write_csv_report(project_dir / "test-reports" / "tuebadz-coverage.csv",
                     ("POS",
                      "Matches",
                      "Mismatches"),
                     ((pos,
                       str(matches[True]),
                       str(matches[False]))
                      for pos, matches in (sorted(stats.items()))
                      if not (pos == "FM" or pos == "XY" or pos.startswith("$"))))

def test_tuebadz_lemmatisation(project_dir, tuebadz, transducer):
    lemmatized = (lemmatize(transducer, w) for s in tuebadz for w in s)
    write_csv_report(project_dir / "test-reports" / "tuebadz-lemmatisation.csv",
                     ("Form",
                      "Lemma",
                      "POS",
                      "DWDSmor-Lemma",
                      "DWDSmor-POS",
                      "Lemma-Match"),
                     ((w.form,
                       w.lemma,
                       w.pos,
                       w.dwdsmor_lemma,
                       w.dwdsmor_pos,
                       w.is_match)
                      for w in lemmatized
                      if not (w.pos == "FM" or w.pos == "XY" or w.pos.startswith("$"))))

def wb_coverage(transducer, wb_entries):
    for wb_n, wb_entry in enumerate(wb_entries):
        lemma = wb_entry["written_repr"]
        analyses = dwdsmor.parse(transducer.analyse(lemma))
        analyzed = False
        analyzed_lemma = ""
        analyzed_pos = ""
        for analysis in analyses:
            if analysis.lemma == lemma:
                analyzed = True
                analyzed_lemma = analysis.lemma or ""
                analyzed_pos = analysis.pos or ""
                break
        yield (wb_entry["file"].as_posix(),
               wb_entry["article_status"],
               lemma,
               wb_entry["pos"],
               wb_entry["inflection_info"],
               analyzed_lemma,
               analyzed_pos,
               ("1" if analyzed else "0"))

def test_wb_coverage(project_dir, transducer, wb_entries):
    write_csv_report(project_dir / "test-reports" / "wb-coverage.csv",
                     ("File",
                      "Article-Status",
                      "Lemma",
                      "POS",
                      "Inflection-Info",
                      "DWDSmor-Lemma",
                      "DWDSmor-POS",
                      "Coverage"),
                     wb_coverage(transducer, wb_entries))
