import os
import csv
import dwdsmor
from collections import namedtuple, defaultdict

# mapping between divergent STTS and SMOR part-of-speech categories
TUEBADZ_DWDSMOR_POS_MAP = {"ADJA":    ["ADJ", "INDEF", "CARD", "ORD"],
                           "ADJD":    ["ADJ"],
                           "ADV":     ["ADV", "ADJ"],
                           "APPO":    ["POSTP"],
                           "APPR":    ["PREP"],
                           "APPRART": ["PREPART"],
                           "APZR":    ["POSTP", "PREP", "ADV"],
                           "ITJ":     ["INTJ"],
                           "KOKOM":   ["CONJ"],
                           "KON":     ["CONJ"],
                           "KOUI":    ["CONJ"],
                           "KOUS":    ["CONJ"],
                           "NE":      ["NPROP"],
                           "NN":      ["NN", "NPROP", "ADJ"],
                           "PDAT":    ["DEM"],
                           "PDS":     ["DEM"],
                           "PIAT":    ["INDEF", "ADJ", "ART"],
                           "PIDAT":   ["INDEF", "DEM", "ADJ"],
                           "PIS":     ["INDEF", "DEM", "ADJ"],
                           "PPER":    ["PPRO"],
                           "PPOSAT":  ["POSS"],
                           "PPOSS":   ["POSS"],
                           "PRELAT":  ["REL"],
                           "PRELS":   ["REL"],
                           "PRF":     ["PPRO"],
                           "PROP":    ["PROADV", "ADV"],
                           "PTKA":    ["PTCL"],
                           "PTKANT":  ["PTCL", "INTJ"],
                           "PTKNEG":  ["PTCL"],
                           "PTKVZ":   ["VPART", "PREP", "ADV", "ADJ"],
                           "PTKZU":   ["PTCL"],
                           "PWAT":    ["WPRO"],
                           "PWAV":    ["PROADV", "ADV"],
                           "PWS":     ["WPRO"],
                           "VAFIN":   ["V"],
                           "VAIMP":   ["V"],
                           "VAINF":   ["V"],
                           "VAPP":    ["V"],
                           "VMFIN":   ["V"],
                           "VMINF":   ["V"],
                           "VMPP":    ["V"],
                           "VVFIN":   ["V"],
                           "VVIMP":   ["V"],
                           "VVINF":   ["V"],
                           "VVIZU":   ["V"],
                           "VVPP":    ["V"],
                           "$.":      ["PUNCT"],
                           "$,":      ["PUNCT"],
                           "$(":      ["PUNCT"]}

# mapping between divergent TüBa-D/Z and DWDSmor lemmas
TUEBADZ_DWDSMOR_LEMMA_MAP = {"ADJA": {"acht": "achte",
                                      "älter": "alt",
                                      "ältest": "alt",
                                      "ältst": "alt",
                                      "ärmer": "arm",
                                      "ärmst": "arm",
                                      "besser": "gut",
                                      "best": "gut",
                                      "bewußt": "bewusst",
                                      "billiger": "billig",
                                      "billigst": "billig",
                                      "breiter": "breit",
                                      "dreier": "drei",
                                      "dritt": "dritte",
                                      "ein": "eine",
                                      "einfachst": "einfach",
                                      "einflußreich": "einflussreich",
                                      "einflußreichst": "einflussreich",
                                      "elft": "elfte",
                                      "enger": "eng",
                                      "engst": "eng",
                                      "erfolgreichst": "erfolgreich",
                                      "erst": "erste",
                                      "freier": "frei",
                                      "fünft": "fünfte",
                                      "genauer": "genau",
                                      "gerechter": "gerecht",
                                      "geringer": "gering",
                                      "geringst": "gering",
                                      "größer": "groß",
                                      "größt": "groß",
                                      "härter": "hart",
                                      "härtest": "hart",
                                      "härtest": "hart",
                                      "häßlich": "hässlich",
                                      "heftigst": "heftig",
                                      "höher": "hoch",
                                      "höchst": "hoch",
                                      "intensiver": "intensiv",
                                      "interessantest": "interessant",
                                      "jünger": "jung",
                                      "jüngst": "jung",
                                      "kleiner": "klein",
                                      "kleinst": "klein",
                                      "klügst": "klug",
                                      "kürzer": "kurz",
                                      "kürzest": "kurz",
                                      "länger": "lang",
                                      "längst": "lang",
                                      "leichter": "leicht",
                                      "liberaler": "liberal",
                                      "links": "link",
                                      "mißglückt": "missglückt",
                                      "modernst": "modern",
                                      "nächst": "nahe",
                                      "näher": "nahe",
                                      "neuer": "neu",
                                      "neuest": "neu",
                                      "neunt": "neunte",
                                      "niedriger": "niedrig",
                                      "niedrigst": "niedrig",
                                      "prominentest": "prominent",
                                      "radikaler": "radikal",
                                      "radikalst": "radikal",
                                      "rechts": "recht",
                                      "reichst": "reich",
                                      "reinst": "rein",
                                      "sämtlich": "sämtliche",
                                      "schärfer": "scharf",
                                      "schlechter": "schlecht",
                                      "schlechtest": "schlecht",
                                      "schlimmer": "schlimm",
                                      "schlimmst": "schlimm",
                                      "schneller": "schnell",
                                      "schnellst": "schnell",
                                      "schwächer": "schwach",
                                      "schwerst": "schwer",
                                      "schwierigst": "schwierig",
                                      "sechst": "sechste",
                                      "selbstbewußt": "selbstbewusst",
                                      "seltenst": "selten",
                                      "sicherst": "sicher",
                                      "siebt": "siebte",
                                      "stärker": "stark",
                                      "stärkst": "stark",
                                      "strenger": "streng",
                                      "teurer": "teuer",
                                      "teuerst": "teuer",
                                      "tiefer": "tief",
                                      "tiefst": "tief",
                                      "unterschiedlichst": "unterschiedlich",
                                      "verfaßt": "verfasst",
                                      "verhaßt": "verhasst",
                                      "verschiedenst": "verschieden",
                                      "viert": "vierte",
                                      "wahrst": "wahr",
                                      "wichtiger": "wichtig",
                                      "wichtigst": "wichtig",
                                      "zehnt": "zehnte",
                                      "zwanzigst": "zwanzigste",
                                      "zweier": "zwei",
                                      "zweit": "zweite",
                                      "zwölft": "zwölfte"},
                             "ADJD": {"aggressiver": "aggressiv",
                                      "älter": "alt",
                                      "ältst": "alt",
                                      "attraktiver": "attraktiv",
                                      "besser": "gut",
                                      "best": "gut",
                                      "besten": "gut",
                                      "bewußt": "bewusst",
                                      "blaß": "blass",
                                      "billiger": "billig",
                                      "brutaler": "brutal",
                                      "deutlicher": "deutlich",
                                      "dicker": "dick",
                                      "dünner": "dünn",
                                      "effektiver": "effektiv",
                                      "einfacher": "einfach",
                                      "enger": "eng",
                                      "erfolgreicher": "erfolgreich",
                                      "ernster": "ernst",
                                      "genauer": "genau",
                                      "gefährlicher": "gefährlich",
                                      "genüßlich": "genüsslich",
                                      "gerechter": "gerecht",
                                      "geringer": "gering",
                                      "größer": "groß",
                                      "größt": "groß",
                                      "günstiger": "günstig",
                                      "härter": "hart",
                                      "häßlich": "hässlich",
                                      "häufiger": "häufig",
                                      "heftiger": "heftig",
                                      "höher": "hoch",
                                      "höchst": "hoch",
                                      "intensiver": "intensiv",
                                      "interessanter": "interessant",
                                      "jünger": "jung",
                                      "jüngst": "jung",
                                      "komplizierter": "kompliziert",
                                      "konkreter": "konkret",
                                      "kraß": "krass",
                                      "klarer": "klar",
                                      "kleiner": "klein",
                                      "kleinst": "klein",
                                      "knapper": "knapp",
                                      "kürzer": "kurz",
                                      "lange": "lang",
                                      "länger": "lang",
                                      "längst": "lang",
                                      "längsten": "lang",
                                      "langsamer": "langsam",
                                      "leichter": "leicht",
                                      "lieber": "lieb",
                                      "liebsten": "lieb",
                                      "meisten": "viel",
                                      "mißtrauisch": "misstrauisch",
                                      "moderner": "modern",
                                      "nächst": "nahe",
                                      "nächsten": "nahe",
                                      "näher": "nahe",
                                      "naß": "nass",
                                      "neuer": "neu",
                                      "neuest": "neu",
                                      "niedriger": "niedrig",
                                      "offener": "offen",
                                      "präziser": "präzis",
                                      "radikaler": "radikal",
                                      "ruhiger": "ruhig",
                                      "sauberer": "sauber",
                                      "schlechter": "schlecht",
                                      "schlimmer": "schlimm",
                                      "schlimmst": "schlimm",
                                      "schlimmsten": "schlimm",
                                      "schneller": "schnell",
                                      "schnellsten": "schnell",
                                      "schnellst": "schnell",
                                      "schöner": "schön",
                                      "schwächer": "schwach",
                                      "schwerer": "schwer",
                                      "schwieriger": "schwierig",
                                      "selbstbewußt": "selbstbewusst",
                                      "seltener": "selten",
                                      "sicherer": "sicher",
                                      "sinnvoller": "sinnvoll",
                                      "später": "spät",
                                      "stärker": "stark",
                                      "stärksten": "stark",
                                      "teurer": "teuer",
                                      "teuerst": "teuer",
                                      "tiefer": "tief",
                                      "ungewiß": "ungewiss",
                                      "unmißverständlich": "unmissverständlich",
                                      "voller": "voll",
                                      "vorsichtiger": "vorsichtig",
                                      "wahrscheinlicher": "wahrscheinlich",
                                      "weitesten": "weit",
                                      "wenigsten": "wenig",
                                      "wichtiger": "wichtig",
                                      "wichtigst": "wichtig"},
                             "ADV": {"eher": "bald",
                                     "ferner": "fern",
                                     "gewiß": "gewiss",
                                     "lieber": "gerne",
                                     "mehr": "sehr",
                                     "öfter": "oft",
                                     "weiter": "weit",
                                     "weniger": "wenig"},
                             "APPR": {"anläßlich": "anlässlich"},
                             "ART": {"das": "die",
                                     "der": "die",
                                     "der|die|das": "die",
                                     "ein": "eine",
                                     "ein|eine": "eine"},
                             "CARD": {"01": "1",
                                      "02": "2",
                                      "03": "3",
                                      "04": "4",
                                      "05": "5",
                                      "06": "6",
                                      "07": "7",
                                      "08": "8",
                                      "09": "9"},
                             "KOUS": {"daß": "dass"},
                             "NE": {"Rußland": "Russland"},
                             "NN": {"Abgeordneter": "Abgeordnete",
                                    "Abgeordneter|Abgeordnete|Abgeordnetes": "Abgeordnete",
                                    "Abhängiger": "Abhängige",
                                    "Abhängiger|Abhängige|Abhängiges": "Abhängige",
                                    "Abriß": "Abriss",
                                    "Abschluß": "Abschluss",
                                    "ähnliches": "ähnlich",
                                    "Aidskranker|Aidskranke|Aidskrankes": "Aidskranke",
                                    "Aids-Kranker|Aids-Kranke|Aids-Krankes": "Aids-Kranke",
                                    "allgemeines": "allgemein",
                                    "Alliierter": "Alliierte",
                                    "Alliierter|Alliierte|Alliiertes": "Alliierte",
                                    "Alter": "Alte",
                                    "Alter|Alte|Altes": "Alte",
                                    "Älterer": "Ältere",
                                    "Älterer|Ältere|Älteres": "Ältere",
                                    "Alternativer|Alternative|Alternatives": "Alternative",
                                    "Anfrag": "Anfrage",
                                    "Angehöriger": "Angehörige",
                                    "Angehöriger|Angehörige|Angehöriges": "Angehörige",
                                    "Angeklagter": "Angeklagte",
                                    "Angeklagter|Angeklagte|Angeklagtes": "Angeklagte",
                                    "Angestellter": "Angestellte",
                                    "Angestellter|Angestellte|Angestelltes": "Angestellte",
                                    "Anlaß": "Anlass",
                                    "Anschluß": "Anschluss",
                                    "Asylsuchender|Asylsuchende|Asylsuchendes": "Asylsuchende",
                                    "Atommüllfaß": "Atommüllfass",
                                    "Aufsichtsratsvorsitzender": "Aufsichtsratsvorsitzende",
                                    "Aufständischer": "Aufständische",
                                    "Aufständischer|Aufständische|Aufständisches": "Aufständische",
                                    "Ausschluß": "Ausschluss",
                                    "Ausschuß": "Ausschuss",
                                    "Äußeres": "Äußere",
                                    "Autonomer": "Autonome",
                                    "Autonomer|Autonome|Autonomes": "Autonome",
                                    "Bankangestellter|Bankangestellte|Bankangestelltes": "Bankangestellte",
                                    "Baß": "Bass",
                                    "Beamter": "Beamte",
                                    "Bediensteter": "Bedienstete",
                                    "Bediensteter|Bedienstete|Bedienstetes": "Bedienstete",
                                    "Befragter": "Befragte",
                                    "Befragter|Befragte|Befragtes": "Befragte",
                                    "Behinderter": "Behinderte",
                                    "Behinderter|Behinderte|Behindertes": "Behinderte",
                                    "Bekannter": "Bekannte",
                                    "Bekannter|Bekannte|Bekanntes": "Bekannte",
                                    "Beschäftigter": "Beschäftigte",
                                    "Beschäftigter|Beschäftigte|Beschäftigtes": "Beschäftigte",
                                    "Beschluß": "Beschluss",
                                    "Beschuldigter": "Beschuldigte",
                                    "Beschuldigter|Beschuldigte|Beschuldigtes": "Beschuldigte",
                                    "besonderes": "besonders",
                                    "Bester": "Beste",
                                    "Bestes": "Beste",
                                    "bestes": "gut",
                                    "Bester|Beste|Bestes": "Beste",
                                    "Beteiligter": "Beteiligte",
                                    "Beteiligter|Beteiligte|Beteiligtes": "Beteiligte",
                                    "Betroffener": "Betroffene",
                                    "Betroffener|Betroffene|Betroffenes": "Betroffene",
                                    "Bewußtsein": "Bewusstsein",
                                    "Biß": "Biss",
                                    "Blinder": "Blinde",
                                    "Blinder|Blinde|Blindes": "Blinde",
                                    "Boß": "Boss",
                                    "Bundestagsabgeordneter": "Bundestagsabgeordnete",
                                    "Bundestagsabgeordneter|Bundestagsabgeordnete|Bundestagsabgeordnetes": "Bundestagsabgeordnete",
                                    "Bündnisgrüner": "Bündnisgrüne",
                                    "Bündnisgrüner|Bündnisgrüne|Bündnisgrünes": "Bündnisgrüne",
                                    "Bürgerschaftsabgeordneter|Bürgerschaftsabgeordnete|Bürgerschaftsabgeordnetes": "Bürgerschaftsabgeordnete",
                                    "Datenschutzbeauftragter": "Datenschutzbeauftragte",
                                    "Delegierter": "Delegierte",
                                    "Delegierter|Delegierte|Delegiertes": "Delegierte",
                                    "Deputierter|Deputierte|Deputiertes": "Deputierte",
                                    "Deutscher": "Deutsche",
                                    "Deutsches": "Deutsche",
                                    "Deutscher|Deutsche|Deutsches": "Deutsche",
                                    "Dritter": "Dritte",
                                    "Drittes": "Dritte",
                                    "Dritter|Dritte|Drittes": "Dritte",
                                    "Drogenabhängiger": "Drogenabhängige",
                                    "Drogenabhängiger|Drogenabhängige|Drogenabhängiges": "Drogenabhängige",
                                    "Drogensüchtiger": "Drogensüchtige",
                                    "Drogensüchtiger|Drogensüchtige|Drogensüchtiges": "Drogensüchtige",
                                    "Drogentoter|Drogentote|Drogentotes": "Drogentote",
                                    "Einfluß": "Einfluss",
                                    "Einflußnahme": "Einflussnahme",
                                    "Eingeborener": "Eingeborene",
                                    "Eingeborener|Eingeborene|Eingeborenes": "Eingeborene",
                                    "Eingemachtes": "Eingemachte",
                                    "Einheimischer": "Einheimische",
                                    "Einheimischer|Einheimische|Einheimisches": "Einheimische",
                                    "einzelner": "einzeln",
                                    "einzelner|einzelne|einzelnes": "einzeln",
                                    "einzelnes": "einzeln",
                                    "Eisheiliger|Eisheilige|Eisheiliges": "Eisheilige",
                                    "Entschluß": "Entschluss",
                                    "Erdgeschoß": "Erdgeschoss",
                                    "Erlaß": "Erlass",
                                    "Erster": "Erste",
                                    "Erstes": "Erste",
                                    "Erster|Erste|Erstes": "Erste",
                                    "Erwachsener": "Erwachsene",
                                    "Erwachsener|Erwachsene|Erwachsenes": "Erwachsene",
                                    "Erwerbstätiger|Erwerbstätige|Erwerbstätiges": "Erwerbstätige",
                                    "Exzeß": "Exzess",
                                    "Familienangehöriger": "Familienangehörige",
                                    "Familienangehöriger|Familienangehörige|Familienangehöriges": "Familienangehörige",
                                    "Faß": "Fass",
                                    "Filmbeauftragter": "Filmbeauftragte",
                                    "Fluß": "Fluss",
                                    "folgendes": "folgend",
                                    "Fraktionsvorsitzender": "Fraktionsvorsitzende",
                                    "Fraktionsvorsitzender|Fraktionsvorsitzende|Fraktionsvorsitzendes": "Fraktionsvorsitzende",
                                    "Französisches": "Französische",
                                    "Freies": "Freie",
                                    "Freier|Freie|Freies": "Freie",
                                    "Freiwilliger": "Freiwillige",
                                    "Freiwilliger|Freiwillige|Freiwilliges": "Freiwillige",
                                    "Fremder": "Fremde",
                                    "Fremder|Fremde|Fremdes": "Fremde",
                                    "Fremdes": "Fremde",
                                    "Friedensprozeß": "Friedensprozess",
                                    "Ganzes": "Ganze",
                                    "Ganzer|Ganze|Ganzes": "Ganze",
                                    "Gefangener": "Gefangene",
                                    "Gefangener|Gefangene|Gefangenes": "Gefangene",
                                    "Geistlicher|Geistliche|Geistliches": "Geistliche",
                                    "Gelehrter": "Gelehrte",
                                    "Geliebter": "Geliebte",
                                    "Genuß": "Genuss",
                                    "geringstes": "gering",
                                    "Geschoß": "Geschoss",
                                    "Getreuer|Getreue|Getreues": "Getreue",
                                    "Gewißheit": "Gewissheit",
                                    "Gläubiger": "Gläubige",
                                    "Gläubiger|Gläubige|Gläubiges": "Gläubige",
                                    "Gleichaltriger|Gleichaltrige|Gleichaltriges": "Gleichaltrige",
                                    "Gleicher": "Gleiche",
                                    "Gleiches": "Gleiche",
                                    "gleiches": "gleich",
                                    "Gleicher|Gleiche|Gleiches": "Gleiche",
                                    "Geschworener": "Geschworene",
                                    "Geschworener|Geschworene|Geschworenes": "Geschworene",
                                    "Grüner": "Grüne",
                                    "Grüner|Grüne|Grünes": "Grüne",
                                    "Haß": "Hass",
                                    "Herrschender": "Herrschende",
                                    "Herrschender|Herrschende|Herrschendes": "Herrschende",
                                    "Heterosexueller": "Heterosexuelle",
                                    "Heterosexueller|Heterosexuelle|Heterosexuelles": "Heterosexuelle",
                                    "Hinterbliebener": "Hinterbliebene",
                                    "Hinterbliebener|Hinterbliebene|Hinterbliebenes": "Hinterbliebene",
                                    "Homosexueller": "Homosexuelle",
                                    "Homosexueller|Homosexuelle|Homosexuelles": "Homosexuelle",
                                    "Hunderttausend": "Hunderttausende",
                                    "Industrieller": "Industrielle",
                                    "Inhaftierter": "Inhaftierte",
                                    "Inhaftierter|Inhaftierte|Inhaftiertes": "Inhaftierte",
                                    "Innerer": "Innere",
                                    "Inneres": "Innere",
                                    "Innerer|Innere|Inneres": "Innere",
                                    "Intellektueller": "Intellektuelle",
                                    "Intellektueller|Intellektuelle|Intellektuelles": "Intellektuelle",
                                    "Jugendlicher": "Jugendliche",
                                    "Jugendlicher|Jugendliche|Jugendliches": "Jugendliche",
                                    "Junger": "Junge",
                                    "Junger|Junge|Junges": "Junge",
                                    "Jüngerer": "Jüngere",
                                    "Jüngerer|Jüngere|Jüngeres": "Jüngere",
                                    "klares": "klar",
                                    "kleines": "klein",
                                    "Kompromiß": "Kompromiss",
                                    "Kongreß": "Kongress",
                                    "Kongreßpartei": "Kongresspartei",
                                    "Konservativer": "Konservative",
                                    "Konservativer|Konservative|Konservatives": "Konservative",
                                    "Kranker": "Kranke",
                                    "Kranker|Kranke|Krankes": "Kranke",
                                    "Kreisvorsitzender": "Kreisvorsitzende",
                                    "Kreisvorsitzender|Kreisvorsitzende|Kreisvorsitzendes": "Kreisvorsitzende",
                                    "Kriminalbeamter": "Kriminalbeamte",
                                    "Krimineller": "Kriminelle",
                                    "Krimineller|Kriminelle|Kriminelles": "Kriminelle",
                                    "Kripobeamter": "Kripobeamte",
                                    "Kulturausschuß": "Kulturausschuss",
                                    "Kulturschaffender": "Kulturschaffende",
                                    "Kulturschaffender|Kulturschaffende|Kulturschaffendes": "Kulturschaffende",
                                    "kurzes": "kurz",
                                    "Kurzschluß": "Kurzschluss",
                                    "Kuß": "Kuss",
                                    "Landesinneres": "Landesinnere",
                                    "Landesvorsitzender": "Landesvorsitzende",
                                    "Landesvorsitzender|Landesvorsitzende|Landesvorsitzendes": "Landesvorsitzende",
                                    "Landtagsabgeordneter": "Landtagsabgeordnete",
                                    "langes": "lang",
                                    "längeres": "lang",
                                    "Lebender|Lebende|Lebendes": "Lebende",
                                    "Leeres": "Leere",
                                    "Lehrender": "Lehrende",
                                    "Lehrender|Lehrende|Lehrendes": "Lehrende",
                                    "Letzter": "Letzte",
                                    "Liberaler": "Liberale",
                                    "Liberaler|Liberale|Liberales": "Liberale",
                                    "Linker": "Linke",
                                    "Linker|Linke|Linkes": "Linke",
                                    "Mächtiger": "Mächtige",
                                    "Mächtiger|Mächtige|Mächtiges": "Mächtige",
                                    "Minderjähriger": "Minderjährige",
                                    "Minderjähriger|Minderjährige|Minderjähriges": "Minderjährige",
                                    "Mißachtung": "Missachtung",
                                    "Mißbrauch": "Missbrauch",
                                    "Mißerfolg": "Misserfolg",
                                    "Mißhandlung": "Misshandlung",
                                    "Mißstand": "Missstand",
                                    "Mißtrauen": "Misstrauen",
                                    "Mißtrauensvotum": "Misstrauensvotum",
                                    "Mißtrauensantrag": "Misstrauensantrag",
                                    "Mißverständnis": "Missverständnis",
                                    "Mitreisender|Mitreisende|Mitreisendes": "Mitreisende",
                                    "Mitwirkender|Mitwirkende|Mitwirkendes": "Mitwirkende",
                                    "Muß": "Muss",
                                    "Nachlaß": "Nachlass",
                                    "neues": "neu",
                                    "neuestes": "neu",
                                    "Nußecke": "Nussecke",
                                    "Obdachloser": "Obdachlose",
                                    "Obdachloser|Obdachlose|Obdachloses": "Obdachlose",
                                    "Offizieller": "Offizielle",
                                    "Offizieller|Offizielle|Offizielles": "Offizielle",
                                    "Oppositioneller": "Oppositionelle",
                                    "Oppositioneller|Oppositionelle|Oppositionelles": "Oppositionelle",
                                    "Orthodoxer": "Orthodoxe",
                                    "Orthodoxer|Orthodoxe|Orthodoxes": "Orthodoxe",
                                    "Ostdeutscher": "Ostdeutsche",
                                    "Ostdeutscher|Ostdeutsche|Ostdeutsches": "Ostdeutsche",
                                    "Parteivorsitzender": "Parteivorsitzende",
                                    "Parteivorsitzender|Parteivorsitzende|Parteivorsitzendes": "Parteivorsitzende",
                                    "Paß": "Pass",
                                    "Politisches": "Politische",
                                    "Polizeibeamter": "Polizeibeamte",
                                    "Polizeibeauftragter": "Polizeibeauftragte",
                                    "Prominenter": "Prominente",
                                    "Prominenter|Prominente|Prominentes": "Prominente",
                                    "Prostituierter": "Prostituierte",
                                    "Prostituierter|Prostituierte|Prostituiertes": "Prostituierte",
                                    "Protestierender": "Protestierende",
                                    "Protestierender|Protestierende|Protestierendes": "Protestierende",
                                    "Prozeß": "Prozess",
                                    "Prozeßtag": "Prozesstag",
                                    "Rechter": "Rechte",
                                    "Rechter|Rechte|Rechtes": "Rechte",
                                    "Redaktionsschluß": "Redaktionsschluss",
                                    "Regierender": "Regierende",
                                    "Regierender|Regierende|Regierendes": "Regierende",
                                    "Reisender": "Reisende",
                                    "Reisender|Reisende|Reisendes": "Reisende",
                                    "Riß": "Riss",
                                    "Roß": "Ross",
                                    "Rückschluß": "Rückschluss",
                                    "Sachverständiger": "Sachverständige",
                                    "Sachverständiger|Sachverständige|Sachverständiges": "Sachverständige",
                                    "Schaulustiger|Schaulustige|Schaulustiges": "Schaulustige",
                                    "Schloß": "Schloss",
                                    "Schluß": "Schluss",
                                    "Schlußfolgerung": "Schlussfolgerung",
                                    "Schlußwort": "Schlusswort",
                                    "Schlußstrich": "Schlussstrich",
                                    "Schuldiger": "Schuldige",
                                    "Schuldiger|Schuldige|Schuldiges": "Schuldige",
                                    "Schuß": "Schuss",
                                    "Schwarzer": "Schwarze",
                                    "Schwarzes": "Schwarze",
                                    "Schwarzer|Schwarze|Schwarzes": "Schwarze",
                                    "Schwuler": "Schwule",
                                    "Schwuler|Schwule|Schwules": "Schwule",
                                    "Selbständiger|Selbständige|Selbständiges": "Selbständige",
                                    "Selbstbewußtsein": "Selbstbewusstsein",
                                    "Sicherheitsbeamter": "Sicherheitsbeamte",
                                    "Sozialer": "Soziale",
                                    "Soziales": "Soziale",
                                    "Sozialer|Soziale|Soziales": "Soziale",
                                    "Standesbeamter": "Standesbeamte",
                                    "Stewardeß": "Stewardess",
                                    "Streikender": "Streikende",
                                    "Streikender|Streikende|Streikendes": "Streikende",
                                    "Streß": "Stress",
                                    "Studierender": "Studierende",
                                    "Studierender|Studierende|Studierendes": "Studierende",
                                    "Süchtiger|Süchtige|Süchtiges": "Süchtige",
                                    "Toter": "Tote",
                                    "Toter|Tote|Totes": "Tote",
                                    "Troß": "Tross",
                                    "Überfluß": "Überfluss",
                                    "Überlebender": "Überlebende",
                                    "Überlebender|Überlebende|Überlebendes": "Überlebende",
                                    "Überschuß": "Überschuss",
                                    "Übersee-Museum": "Überseemuseum",
                                    "übriges": "übrig",
                                    "Umriß": "Umriss",
                                    "Unbekannter": "Unbekannte",
                                    "Unbekannter|Unbekannte|Unbekanntes": "Unbekannte",
                                    "Unbeteiligter|Unbeteiligte|Unbeteiligtes": "Unbeteiligte",
                                    "Uniformierter|Uniformierte|Uniformiertes": "Uniformierte",
                                    "Untersuchungsausschuß": "Untersuchungsausschuss",
                                    "Verantwortlicher": "Verantwortliche",
                                    "Verantwortlicher|Verantwortliche|Verantwortliches": "Verantwortliche",
                                    "Verbündeter": "Verbündete",
                                    "Verbündeter|Verbündete|Verbündetes": "Verbündete",
                                    "Verdächtiger": "Verdächtige",
                                    "Verdächtiger|Verdächtige|Verdächtiges": "Verdächtige",
                                    "Verfolgter": "Verfolgte",
                                    "Verfolgter|Verfolgte|Verfolgtes": "Verfolgte",
                                    "Verhafteter|Verhaftete|Verhaftetes": "Verhaftete",
                                    "Verletzter": "Verletzte",
                                    "Verletzter|Verletzte|Verletztes": "Verletzte",
                                    "Verrückter": "Verrückte",
                                    "Vertriebener": "Vertriebene",
                                    "Vertriebener|Vertriebene|Vertriebenes": "Vertriebene",
                                    "Verurteilter": "Verurteilte",
                                    "Verurteilter|Verurteilte|Verurteiltes": "Verurteilte",
                                    "Verwandter": "Verwandte",
                                    "Verwandter|Verwandte|Verwandtes": "Verwandte",
                                    "Volkskongreß": "Volkskongress",
                                    "Vorgesetzter": "Vorgesetzte",
                                    "Vorgesetzter|Vorgesetzte|Vorgesetztes": "Vorgesetzte",
                                    "Vorsitzender": "Vorsitzende",
                                    "Vorsitzender|Vorsitzende|Vorsitzendes": "Vorsitzende",
                                    "Vorstandsvorsitzender": "Vorstandsvorsitzende",
                                    "Vorstandsvorsitzender|Vorstandsvorsitzende|Vorstandsvorsitzendes": "Vorstandsvorsitzende",
                                    "Wahlberechtigter": "Wahlberechtigte",
                                    "Wahlberechtigter|Wahlberechtigte|Wahlberechtigtes": "Wahlberechtigte",
                                    "Wehrschloß": "Wehrschloss",
                                    "Weißer": "Weiße",
                                    "Weißer|Weiße|Weißes": "Weiße",
                                    "weitem": "weit",
                                    "weites": "weit",
                                    "weiteres": "weiter",
                                    "wesentlichen": "wesentlich",
                                    "wesentliches": "wesentlich",
                                    "Westdeutscher|Westdeutsche|Westdeutsches": "Westdeutsche",
                                    "Wohnungssuchender|Wohnungssuchende|Wohnungssuchendes": "Wohnungssuchende",
                                    "Zivilbeamter": "Zivilbeamte",
                                    "Zusammenschluß": "Zusammenschluss",
                                    "Zuschuß": "Zuschuss",
                                    "Zweiter": "Zweite",
                                    "Zweites": "Zweite",
                                    "Zweiter|Zweite|Zweites": "Zweite"},
                             "PDAT": {"alles": "alle",
                                      "dasjenige": "diejenige",
                                      "das": "die",
                                      "der": "die",
                                      "der|die|das": "die",
                                      "deren": "die",
                                      "derjenige": "diejenige",
                                      "derjenige|diejenige|dasjenige": "diejenige",
                                      "dessen": "die",
                                      "dessen|deren": "die",
                                      "dieser": "diese",
                                      "dieser|diese|dieses": "diese",
                                      "dieses": "diese",
                                      "jener": "jene",
                                      "jener|jene|jenes": "jene",
                                      "jenes": "jene"},
                             "PDS": {"dasjenige": "diejenige",
                                     "derjenige": "diejenige",
                                     "das": "die",
                                     "der": "die",
                                     "der|die|das": "die",
                                     "derjenige|diejenige|dasjenige": "diejenige",
                                     "dieser": "diese",
                                     "dieser|diese|dieses": "diese",
                                     "dieses": "diese",
                                     "jener": "jene",
                                     "jener|jene|jenes": "jene",
                                     "jenes": "jene"},
                             "PIAT": {"einiger": "einige",
                                      "einiger|einige|einiges": "einige",
                                      "einiges": "einige",
                                      "irgendein": "irgendeine",
                                      "irgendwelcher": "irgendwelche",
                                      "irgendwelcher|irgendwelche|irgendwelches": "irgendwelche",
                                      "irgendwelches": "irgendwelche",
                                      "kein": "keine",
                                      "keiner": "keine",
                                      "kein|keine": "keine",
                                      "keines": "keine",
                                      "mancher": "manche",
                                      "mancher|manche|manches": "manche",
                                      "manches": "manche",
                                      "mehr": "viel",
                                      "weniger": "wenig"},
                             "PIDAT": {"all": "alle",
                                       "alles": "alle",
                                       "bißchen": "bisschen",
                                       "jeder": "jede",
                                       "jedes": "jede",
                                       "jeglich": "jegliche",
                                       "jeglicher": "jegliche",
                                       "jegliches": "jegliche",
                                       "manch": "manche",
                                       "meisten": "viel",
                                       "meistes": "viel",
                                       "sämtlich": "sämtliche",
                                       "solch": "solche",
                                       "solcher": "solche",
                                       "solcher|solche|solches": "solche",
                                       "solches": "solche",
                                       "viele": "viel",
                                       "vieler": "viel",
                                       "vieler|viele|vieles": "viel",
                                       "vieles": "viel",
                                       "wenige": "wenig",
                                       "weniger": "wenig",
                                       "wenigste": "wenig"},
                             "PIS": {"alles": "alle",
                                     "andere": "ander",
                                     "anderer": "ander",
                                     "anderer|andere|anderes": "ander",
                                     "anderes": "ander",
                                     "bißchen": "bisschen",
                                     "beides": "beide",
                                     "ein|eine": "eine",
                                     "einer": "eine",
                                     "eines": "eine",
                                     "einiges": "einige",
                                     "einzige": "einzig",
                                     "einziger": "einzig",
                                     "einziger|einzige|einziges": "einzig",
                                     "einziges": "einzig",
                                     "ersterer": "erstere",
                                     "ersterer|erstere|ersteres": "erstere",
                                     "ersteres": "erstere",
                                     "jeder": "jede",
                                     "jeder|jede|jedes": "jede",
                                     "jedes": "jede",
                                     "keiner": "keine",
                                     "letzterer": "letztere",
                                     "letzterer|letztere|letzteres": "letztere",
                                     "letzteres": "letztere",
                                     "keiner|keine|keines": "keine",
                                     "keines": "keine",
                                     "mancher": "manche",
                                     "mancher|manche|manches": "manche",
                                     "manches": "manche",
                                     "mehr": "viel",
                                     "meisten": "viel",
                                     "meistes": "viel",
                                     "solch": "solche",
                                     "solcher": "solche",
                                     "solcher|solche|solches": "solche",
                                     "solches": "solche",
                                     "viele": "viel",
                                     "vieler": "viel",
                                     "vieler|viele|vieles": "viel",
                                     "vieles": "viel",
                                     "wenige": "wenig",
                                     "weniger": "wenig",
                                     "wenigst": "wenig"},
                             "PPER": {"er|sie|es": "er"},
                             "PPOSAT": {"dein": "deine",
                                        "dein|deine": "deine",
                                        "deiner": "deine",
                                        "euer": "eure",
                                        "euer|eure": "eure",
                                        "ihr": "ihre",
                                        "ihr|ihre": "ihre",
                                        "mein": "meine",
                                        "mein|meine": "meine",
                                        "sein": "seine",
                                        "sein|seine": "seine",
                                        "unser": "unsere",
                                        "unser|unsere": "unsere"},
                             "PPOSS": {"deines": "deine",
                                       "ihres": "ihre",
                                       "Ihres": "ihre",
                                       "mein|meine": "meine",
                                       "meiner|meine|mein": "meine",
                                       "meines": "meine",
                                       "meiner": "meine",
                                       "Seine": "seine",
                                       "seiner": "seine",
                                       "Seiner": "seine",
                                       "seiner|seine|seines": "seine",
                                       "Seiner|Seine|Seines": "seine",
                                       "seines": "seine",
                                       "Seines": "seine",
                                       "unser": "unsere",
                                       "unserer": "unsere",
                                       "unserer|unsere|unseres": "unsere",
                                       "Unsriger|Unsrige|Unsriges": "unsrige"},
                             "PRELAT": {"deren": "die",
                                        "dessen": "die",
                                        "dessen|deren": "die"},
                             "PRELS": {"das": "die",
                                       "der": "die",
                                       "der|die|das": "die",
                                       "welcher": "welche",
                                       "welcher|welche|welches": "welche",
                                       "welches": "welche"},
                             "PRF": {"dir": "dich",
                                     "mir": "mich"},
                             "PTKANT": {"ja_ja_": "jaja",
                                        "nein_": "nee"},
                             "PTKVZ": {"Heraus": "heraus",
                                       "Hinzu": "hinzu",
                                       "Zurück": "zurück"},
                             "PWAT": {"welch": "welche",
                                      "welcher": "welche",
                                      "welcher|welche|welches": "welche",
                                      "welches": "welche",
                                      "wessen": "was",
                                      "wievieler": "wieviele",
                                      "wievieler|wieviele|wievieles": "wieviele",
                                      "wievieles": "wieviele"},
                             "PWS": {"welcher": "welche",
                                     "welcher|welche|welches": "welche",
                                     "welches": "welche"}}

def tuebadz_to_dwdsmor_pos_list(pos):
    if pos in TUEBADZ_DWDSMOR_POS_MAP:
        return TUEBADZ_DWDSMOR_POS_MAP[pos]
    else:
        return pos

def tuebadz_to_dwdsmor_lemma(pos, lemma):
    if pos in TUEBADZ_DWDSMOR_LEMMA_MAP and lemma in TUEBADZ_DWDSMOR_LEMMA_MAP[pos]:
        return TUEBADZ_DWDSMOR_LEMMA_MAP[pos][lemma]
    else:
        return lemma

LemmatizedWord = namedtuple("LemmatizedWord", ("form",
                                               "lemma",
                                               "pos",
                                               "dwdsmor_lemma",
                                               "dwdsmor_pos",
                                               "is_match"))

def lemmatize(transducer, w):
    form, lemma, pos = (w.get("form", ""), w.get("lemma", ""), w.get("pos", ""))
    dwdsmor_lemma = ""
    dwdsmor_pos = ""
    if pos == "PTKVZ" or lemma == "#refl":
        lemma = form
    lemma = lemma.split("%")[0]
    lemma = lemma.replace("#", "")
    analyses = tuple(dwdsmor.parse(transducer.analyse(form)))
    # analyses with matching part-of-speech categories
    analyses_with_matching_pos = tuple(a for a in analyses
                                       if a.pos in tuebadz_to_dwdsmor_pos_list(pos))
    # analyses with matching lemmas of matching part-of-speech categories
    analyses_with_matching_lemma = tuple(a for a in analyses_with_matching_pos
                                         if tuebadz_to_dwdsmor_lemma(pos, lemma) == a.lemma)
    # first consider analyses with matching lemmas of matching part-of-speech categories
    if len(analyses_with_matching_lemma) > 0:
        dwdsmor_lemma = analyses_with_matching_lemma[0].lemma
        dwdsmor_pos   = analyses_with_matching_lemma[0].pos
    # else consider any lemmas of matching part-of-speech categories
    elif len(analyses_with_matching_pos) > 0:
        dwdsmor_lemma = analyses_with_matching_pos[0].lemma
        dwdsmor_pos   = analyses_with_matching_pos[0].pos
    if (pos == "VAFIN" or pos == "VMFIN" or pos == "VVFIN" or pos == "VVIMP") and len(dwdsmor_lemma) > 0:
        # TüBa-D/Z lemmas for finite verb forms of particle verbs include the particle
        # while DWDSmor lemmas do not.
        is_match = tuebadz_to_dwdsmor_lemma(pos, lemma).endswith(dwdsmor_lemma)
    else:
        is_match = tuebadz_to_dwdsmor_lemma(pos, lemma) == dwdsmor_lemma
    return LemmatizedWord(form,
                          lemma,
                          pos,
                          dwdsmor_lemma,
                          dwdsmor_pos,
                          is_match)

def write_csv_report(csv_report_file, csv_header, csv_rows):
    csv_report_file.parent.mkdir(parents=True, exist_ok=True)
    with csv_report_file.open("w") as report_f:
        report_writer = csv.writer(report_f, lineterminator=os.linesep)
        report_writer.writerow(csv_header)
        for csv_row in csv_rows:
            report_writer.writerow(csv_row)

def test_tuebadz_coverage(project_dir, tuebadz, transducer):
    lemmatized = (lemmatize(transducer, w) for s in tuebadz for w in s)
    stats = defaultdict(lambda: defaultdict(int))
    for w in lemmatized:
        stats[w.pos][w.is_match] += 1
    write_csv_report(project_dir / "test-reports" / "tuebadz-coverage.csv",
                     ("POS",
                      "Matches",
                      "Mismatches"),
                     ((pos,
                       str(matches[True]),
                       str(matches[False]))
                      for pos, matches in (sorted(stats.items()))))

def test_tuebadz_lemmatisation(project_dir, tuebadz, transducer):
    lemmatized = (lemmatize(transducer, w) for s in tuebadz for w in s)
    write_csv_report(project_dir / "test-reports" / "tuebadz-lemmatisation.csv",
                     ("Form",
                      "Lemma",
                      "POS",
                      "DWDSmor-Lemma",
                      "DWDSmor-POS",
                      "Lemma-Match"),
                     ((w.form,
                       w.lemma,
                       w.pos,
                       w.dwdsmor_lemma,
                       w.dwdsmor_pos,
                       w.is_match)
                      for w in lemmatized))

def wb_coverage(transducer, wb_entries):
    for wb_n, wb_entry in enumerate(wb_entries):
        lemma = wb_entry["written_repr"]
        analyses = dwdsmor.parse(transducer.analyse(lemma))
        analyzed = False
        analyzed_lemma = ""
        analyzed_pos = ""
        for analysis in analyses:
            if analysis.lemma == lemma:
                analyzed = True
                analyzed_lemma = analysis.lemma or ""
                analyzed_pos = analysis.pos or ""
                break
        yield (wb_entry["file"].as_posix(),
               wb_entry["article_status"],
               lemma,
               wb_entry["pos"],
               wb_entry["inflection_info"],
               analyzed_lemma,
               analyzed_pos,
               ("1" if analyzed else "0"))

def test_wb_coverage(project_dir, transducer, wb_entries):
    write_csv_report(project_dir / "test-reports" / "wb-coverage.csv",
                     ("File",
                      "Article-Status",
                      "Lemma",
                      "POS",
                      "Inflection-Info",
                      "DWDSmor-Lemma",
                      "DWDSmor-POS",
                      "Coverage"),
                     wb_coverage(transducer, wb_entries))
