#!/bin/bash

# Bulds happen in the WORK area
base_dir=/scratch/usr/bembbaw0
pushd $base_dir/dwdsmor

# Check that a lexicon has been provided/uploaded
if [ ! -f SMORLemma/lexicon/lexicon ]; then
    echo "No lexicon provided!"
    exit 1
fi

source .venv/bin/activate
make
