#!/bin/bash

# Prepare build environment in WORK area
base_dir=/scratch/usr/bembbaw1
pushd $base_dir

# SFST needs cmake v3.1 and a recent C++ compiler; both are available via the
# module system
module load cmake/3.16.2 gcc/9.3.0
export CC=$(which gcc)
export CXX=$(which g++)

# SFST needs flex v2.6.4; HLRN only provides v2.5, so we need to install from
# source.
flex_dir=$base_dir/flex-2.6.4
if [ ! -d $flex_dir ]; then
    curl -LO https://github.com/westes/flex/releases/download/v2.6.4/flex-2.6.4.tar.gz
    tar xzf flex-2.6.4.tar.gz
    pushd $flex_dir
    ./configure && make
    popd
fi
export PATH=$flex_dir/src:$PATH

sfst_dir=$base_dir/sfst-1.5.5
if [ ! -d $sfst_dir ]; then
    curl -L -o sfst-1.5.5.tar.gz https://github.com/santhoshtr/sfst/archive/refs/tags/1.5.5.tar.gz
    tar xzf sfst-1.5.5.tar.gz
    pushd $sfst_dir
    mkdir build
    (cd build && cmake .. && make)
    popd
fi

export PATH=$sfst_dir/build/src:$PATH
export LD_LIBRARY_PATH=$sfst_dir/build/src:$LD_LIBRARY_PATH

pushd $base_dir/dwdsmor

# TODO: consider conda environments
if [ ! -d .venv ]; then
    python3 -m venv .venv
fi
source .venv/bin/activate

exec make setup
