name: Release Please
on:
  push:
    branches:
      - dev
permissions:
  contents: write
  pull-requests: write
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RP_TOKEN }}
          release-type: python
          target-branch: ${{ github.ref_name }}
